version: '3.8'

services:
  wikimedia-crawler:
    build: .
    container_name: wikimedia-dumps-crawler
    environment:
      - DATABUS_API_KEY=${DATABUS_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./crawled_urls.txt:/app/crawled_urls.txt
    restart: unless-stopped
    
    # For monthly cron job mode - uncomment the lines below
    # command: /bin/bash -c "
    #   echo '0 2 1 * * cd /app && ./crawl_publish.sh >> /app/logs/cron.log 2>&1' | crontab - &&
    #   cron -f"
    
    # For one-time execution (default)
    command: ./crawl_publish.sh

  # Optional Add a monitoring service
  log-viewer:
    image: amir20/dozzle:latest
    container_name: wikimedia-logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
    environment:
      - DOZZLE_LEVEL=info
    profiles:
      - monitoring
